version: "3"
services:
  photon:
    build: 
        context: .
        dockerfile: Docker/Dockerfile_photon
        args: 
           - photon_data=Docker/photon.tar.gz
    ports:
      - "2322:2322"
      
  libpostal:
    build: 
        context: .
        dockerfile: Docker/Dockerfile_libpostal
    ports:
            - "7070:8080"
    environment: 
      - NB_LPOST_WORKERS:1

  wrapper:
          #network_mode: host
    build: 
        context: .
        dockerfile: Docker/Dockerfile_wrapper
    ports:
      - "5000:5000"
    environment:
      - NB_WORKERS:4
      - PHOTON_HOST=photon:2322
      - LPOST_HOST=libpostal:8080
      - OSM_HOST=10.1.0.45:8081 #172.17.0.2:8080 #172.17.0.2:8080  #10.1.0.45:7070
      - LOG_LEVEL=high
#       - TRANSFORMERS=[ ["orig"],
#                           ["regex[init]"],
#                           ["nonum"],
#                           ["libpostal", "regex[lpost]"], 
#                           ["libpostal", "regex[lpost]", "nonum"], 
#                           ["libpostal", "regex[lpost]", "photon"], 
#                           ["libpostal", "regex[lpost]", "photon", "nonum"], 
#                           ["photon"],
#                           ["photon", "nonum"],
#                           ["libpostal", "nostreet"], 
#                           ["nostreet"]
#                         ]
      
